# Generated by Django 3.0.9 on 2020-08-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_profile_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_profile',
            old_name='Company_name',
            new_name='Name',
        ),
    ]
