# Generated by Django 3.0.9 on 2020-08-07 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200807_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='job_seeker_profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job_seeker_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
