# Generated by Django 3.0.9 on 2020-08-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200807_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'admin'), (1, 'company'), (2, 'job_seeker')]),
        ),
    ]
