# Generated by Django 3.0.9 on 2020-08-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_profile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='company_profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.City'),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Country'),
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.City'),
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Country'),
        ),
    ]
