# Generated by Django 3.0.9 on 2020-08-09 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200809_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_profile',
            name='building_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='street',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_profile',
            name='zip_code',
            field=models.CharField(default=1, max_length=12, verbose_name='ZIP / Postal code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='CV',
            field=models.FileField(default=1, upload_to='CV/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='country_of_residence',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='cover_letter',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='house_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='personal_photo',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='street',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='surname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='zip_code',
            field=models.CharField(default=1, max_length=12, verbose_name='ZIP / Postal code'),
            preserve_default=False,
        ),
    ]
